DROP TABLE IF EXISTS TODO;

CREATE TABLE TODO (
    ID INT NOT NULL AUTO_INCREMENT
  , TITLE VARCHAR(60) NOT NULL
  , COMPLETED BOOLEAN NOT NULL
  , `ORDERS` INT(11) DEFAULT NULL
  , `URL` VARCHAR(255) NOT NULL
  , PRIMARY KEY (ID)
);
